package norman.gurps.create.model;

public enum Affected {
    OTHER_ATTRIBUTES_DODGE, OTHER_ATTRIBUTES_FRIGHT_CHECK, OTHER_ATTRIBUTES_MENTAL_STUN_CHECK,
    OTHER_ATTRIBUTES_DEATH_CHECK, OTHER_ATTRIBUTES_PHYSICAL_STUN_CHECK
}
